const info ={
    usuario: {
        email: 'lolopelle1@gmail.com'
        usuario: 'lolosoljoaco'
        contrasenia:'0987654321'
        fecha_de_nacimiento: '18/05/2005'
        numero_documento:'52800016'
        foto:
    },

    productos:[
        {
        imagen:
        nombre: 
        foto:
        comentarios:[
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
        ]
        },
        {
        imagen:
        nombre: 
        foto:
        comentarios:[
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
        ]
        },
        {
        imagen:
        nombre: 
        foto:
        comentarios:[
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
        ]
        },
        {
        imagen:
        nombre: 
        foto:
        comentarios:[
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
        ]
        },
        {
        imagen:
        nombre: 
        foto:
        comentarios:[
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
        ]
        },
        {
        imagen:
        nombre: 
        foto:
        comentarios:[
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
        ]
        },
        {
        imagen:
        nombre: 
        foto:
        comentarios:[
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
        ]
        },
        {
        imagen:
        nombre: 
        foto:
        comentarios:[
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
        ]
        },
        {
        imagen:
        nombre: 
        foto:
        comentarios:[
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
        ]
        }, 
        {
        imagen:
        nombre: 
        foto:
        comentarios:[
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
            {
                user:
                comentario:
                foto_de_perfil:
            },
        ]
        },   
    ]
    }

